sudo: required

services:
  - docker

language: scala
scala: 2.11.7
jdk: oraclejdk8
script: mvn package

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker build -t eneco/kafka-connect-nationalgrid;
    docker push eneco/kafka-connect-nationalgrid;
    fi